title: Ice Cellar Project
theme: jekyll-theme-architect
descriptions:
collections:
  projects:
    output: true
defaults:
  - scope:
      path: "_setting_up"
      type: 
    values:
      layout: page
